### ISSUE TITLE
player invincibility frames

### ISSUE THREAD

**Issue by ivanheinemeier** [tobiasbp/python-arcade-dungeon#83]
There must be a cooldown on how often the player can get hit by an enemy. Currently the enemy weapon tabs nearly 400 hp/sec, despite its weapon damage being 7.

**Comment by turell4k** [comment]
Make the weapon hitbox disappear after it has hit a player

**Comment by turell4k** [comment]
attack point which only exists in the single frame in which the attack is made. check if point is inside player hitbox
